# Generated by Django 5.2.7 on 2025-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngay', models.DateTimeField(auto_now_add=True)),
                ('NoiDung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BietOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngay', models.DateTimeField(auto_now_add=True)),
                ('NoiDung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MuonLam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngay', models.DateTimeField(auto_now_add=True)),
                ('NoiDung', models.TextField()),
            ],
        ),
    ]
